# Generated by Django 4.2.16 on 2024-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_books'),
        ('books', '0002_remove_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
