# Generated by Django 4.2.16 on 2024-10-03 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_book_status'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrow',
            new_name='Loan',
        ),
    ]
