# Generated by Django 4.2.16 on 2024-10-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_rename_borrow_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
