# Generated by Django 4.2.16 on 2024-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_categories'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
